version: "3.8"

services:
    app:
        networks:
            - default
        build: .
        volumes:
            - ./:/home/python/app
        ports:
            - 8000:8000
        extra_hosts:
            - "host.docker.internal:172.17.0.1"
networks:
    default:
        external:
            name: kafka_default
